codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 20..100
    round: down
    precision: 2
    status:
      project:
        default:
          threshold: .1
          base: pr

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: feature/tests
        flags: null
        attachments: "sunburst, diff"
        paths: null
        message: "Coverage {{changed}} for {{owner}}/{{repo}}"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: off

ignore:
  - "src/etc"
  - "src/migrations"
  - "src/templates"
  - "src/translations"
  - "src/web/assets"
  - "docs"
  - "templates"
  - "tests"
  - "vendor"